#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "opcache-gui"
name = "OPcache GUI"
description.en = "Effective and responsive interface for Zend OPcache"
description.fr = "Interface efficace et réactive pour Zend OPcache"

version = "3.5.5~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/amnuts/opcache-gui"
fund = "https://github.com/sponsors/amnuts"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/opcache"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/amnuts/opcache-gui/archive/refs/tags/3.5.5.tar.gz"
    sha256 = "0076e354700f897511c23dffeb15c0ca92980cf9ffa35aa24bda5e3fdc3e77d4"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3-fpm"

